  version: '3.8'

  services:
    node-app:
      build:
        context: .
        dockerfile: Dockerfile
      working_dir: /usr/src/app
      ports:
        - '5002:3000'
      environment:
        - NODE_ENV=development
        - PORT=3000
        - MONGO_URI=mongodb://localhost:27017/encodelabs
      depends_on:
        - mongo

    mongo:
      image: mongo:latest
      ports:
        - '27017:27017'
      volumes:
        - mongo-data:/data/db

  volumes:
    mongo-data:
